# Generated by Django 3.2.9 on 2022-04-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_image', models.ImageField(upload_to='images')),
                ('upload_sign', models.ImageField(upload_to='images')),
                ('passport_number', models.CharField(max_length=256)),
                ('given_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
            ],
        ),
    ]
